### PR TITLE
Portland is past.

### PR DESCRIPTION
**Pull request by plaindocs**
We really should have these two files in the same format, so we can just copy paste...

### CODE REVIEW

**Comment by ericholscher** [comment]
The old conferences live offsite, so we can't use :doc: links. Feel free to use a :doc: link for the ones on the current site.

**Comment by plaindocs** [comment]
What about using non doc links for current ones as well?

**Comment by ericholscher** [comment]
Makes sense.

**Comment by plaindocs** [comment]
Except you can't easily copy paste the multi line format anyway. Gah.

**Pull request merged**
